### PR TITLE
added install instructions for Ubuntu in README

### PR DESCRIPTION
**Pull request by UnixJunkie**
Ubuntu is the most widely used Linux distro, plus there are chances it will work the same in Debian.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Thanks to @jaimergp for help getting this to work.

**Comment by UnixJunkie** [comment]
Not sure this is relevant, but there may be a fix needed on the chimera side:
```
mv ~/usr/chimera-1.13/lib/libz.so.1 ~/usr/chimera-1.13/lib/libz.so.1.bck
mv ~/usr/chimera-1.13/lib/libgomp.so.1.bck ~/usr/chimera-1.13/lib/libgomp.so.1.bck
```

**Comment by UnixJunkie** [comment]
Also, we install libtangram and tangram_plipgui from archive/master.zip.
This is not cool.
We should install tagged version of software, so that users have a reproducible
way to install the software and get things working.
Only developers should need to install untagged version of software.

**Comment by jaimergp** [comment]
Thanks for the PR!

I will tag a new release for both packages so you can use `[...]/archive/vX.Y.Z.zip` links in the README.

**Comment by jaimergp** [comment]
Tag added. You can use `https://github.com/insilichem/tangram_plipgui/archive/v0.0.2.zip` and `https://github.com/insilichem/libtangram/archive/v0.0.2.zip` now.

**Comment by UnixJunkie** [comment]
thanks, I updated the README in this PR

**Comment by jaimergp** [comment]
Perfect! Merged!

**Pull request merged**
